const categories = require('./categories/categories.service.js');
const paymentManagement = require('./payment_management/payment_management.service.js');
const systemuser = require('./systemuser/systemuser.service.js');
const shop = require('./shop/shop.service.js');
const socialMediaManagement = require('./social_media_management/social_media_management.service.js');
const announcements = require('./announcements/announcements.service.js');
const adminUploads = require('./admin-uploads/admin-uploads.service.js');
const shopper = require('./shopper/shopper.service.js');
const featuredPhotos = require('./featured-photos/featured-photos.service.js');
const storeAdvertisment = require('./store-advertisment/store-advertisment.service.js');
const storeSchedule = require('./store-schedule/store-schedule.service.js');
const storeUsers = require('./store-users/store-users.service.js');
const products = require('./products/products.service.js');
const services = require('./services/services.service.js');
const store = require('./store/store.service.js');
const storeFuelDelivery = require('./store-fuel-delivery/store-fuel-delivery.service.js');
const storeInventory = require('./store-inventory/store-inventory.service.js');
const users = require('./users/users.service.js');
const storePayments = require('./store-payments/store-payments.service.js');
const cart = require('./cart/cart.service.js');
const shopperPayments = require('./shopper_payments/shopper_payments.service.js');
const productTransactions = require('./product-transactions/product-transactions.service.js');
const serviceTransactions = require('./service-transactions/service-transactions.service.js');
const giftRegistry = require('./gift-registry/gift-registry.service.js');
const productAdvertisment = require('./product-advertisment/product-advertisment.service.js');
const serviceAdvertisment = require('./service-advertisment/service-advertisment.service.js');
const paymentUtilities = require('./payment-utilities/payment-utilities.service.js');
const reportStoreTransactions = require('./report-store-transactions/report-store-transactions.service.js');
const reportSales = require('./report-sales/report-sales.service.js');
const productSubscriptions = require('./product-subscriptions/product-subscriptions.service.js');
const serviceSubscriptions = require('./service-subscriptions/service-subscriptions.service.js');
const gallerySubscription = require('./gallery-subscription/gallery-subscription.service.js');
const itemSubscriptions = require('./item-subscriptions/item-subscriptions.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(categories);
  app.configure(paymentManagement);
  app.configure(systemuser);
  app.configure(shop);
  app.configure(socialMediaManagement);
  app.configure(announcements);
  app.configure(adminUploads);
  app.configure(shopper);
  app.configure(featuredPhotos);
  app.configure(storeAdvertisment);
  app.configure(storeSchedule);
  app.configure(storeUsers);
  app.configure(products);
  app.configure(services);
  app.configure(store);
  app.configure(storeFuelDelivery);
  app.configure(storeInventory);
  app.configure(users);
  app.configure(storePayments);
  app.configure(cart);
  app.configure(shopperPayments);
  app.configure(productTransactions);
  app.configure(serviceTransactions);
  app.configure(giftRegistry);
  app.configure(productAdvertisment);
  app.configure(serviceAdvertisment);
  app.configure(paymentUtilities);
  app.configure(reportStoreTransactions);
  app.configure(reportSales);
  app.configure(productSubscriptions);
  app.configure(serviceSubscriptions);
  app.configure(gallerySubscription);
  app.configure(itemSubscriptions);
};
